name: Newman HTMLExtra with GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3

      - name: Fetch Postman Collection
        run: |
          curl -sSL \
            -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_UID }}" \
            -o reqres_collection.postman_collection.json

      - name: Fetch Postman Environment
        run: |
          curl -sSL \
            -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            "https://api.getpostman.com/environments/${{ secrets.POSTMAN_ENV_UID }}" \
            -o reqres_environment.postman_environment.json

      - name: Commit updated Postman files to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase origin main || true
          git add reqres_collection.postman_collection.json reqres_environment.postman_environment.json
          git commit -m "Auto-sync from Postman" || echo "No changes"
          git push origin main || echo "No changes to push"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman & HTMLExtra
        run: npm install -g newman@6.1.2 newman-reporter-htmlextra@1.23.1

      - name: Run Newman tests with HTMLExtra
        id: run_tests
        continue-on-error: true
        run: |
          mkdir -p public
          newman run reqres_collection.postman_collection.json \
            -e reqres_environment.postman_environment.json \
            -r htmlextra \
            --reporter-htmlextra-export public/index.html \
            --reporter-htmlextra-title "API Tests" \
            --reporter-htmlextra-includesequence \
            --reporter-htmlextra-charts

      # Deploy only if tests passed
      - name: Deploy HTMLExtra report to GitHub Pages
        if: steps.run_tests.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

      # Optional: mark workflow as failed if tests failed
      - name: Fail workflow if tests failed
        if: steps.run_tests.outcome != 'success'
        run: exit 1
